### ISSUE TITLE
serve via HTTPS

### ISSUE THREAD

**Issue by afeld** [consul/website#11]
Not sure how it's deployed, but this would be good for the main site to have.

**Comment by milovanderlinden** [comment]
I have this set up. It is actually not that hard. When serving through github-pages and when the A and CNAME records are set up correctly with the DNS, github pages will fire a certificate through letsencrypt. This may take up to 24 hours, but after that, you can set the site to __enforce https__ and it will show up correctly like with http://consulproject.nl (that gets redirected to https thanks to this function)

**Comment by afeld** [comment]
Since I believe the site is static, one option would be moving to hosting that provides this built-in, like GitHub Pages or Netlify.

**Comment by decabeza** [comment]
This page is already using `https`. 🎉 

![https](https://user-images.githubusercontent.com/631897/84382377-d015ad80-abea-11ea-8984-1d9f9a120984.png)
