### ISSUE TITLE
Arroyomolinos - consul url and logo request

### ISSUE THREAD

**Issue by milovanderlinden** [consul/website#13]
I found a listing for Arroyomolinos in the markers that has no url and no logo. Can these be provided so I can update my organizations.json?

**Comment by milovanderlinden** [comment]
Ok, logo found. Now all I would like is the link to their implementation of Consul.

**Comment by decabeza** [comment]
Hi @milovanderlinden,

You can find Arroyomolinos CONSUL impementation in https://decide.ayto-arroyomolinos.org/.

😌
