### ISSUE TITLE
no instructions

### ISSUE THREAD

**Issue by john11smith** [consul/website#17]
I have no Idea how it supposed to work? For me just says:
"--- layout: application locale: en ref: homepage --- {% include index.html %} "
could not find explanations in the code either.

**Comment by decabeza** [comment]
Hi @john11smith,

This site it's built using [Jekyll gem](https://jekyllrb.com/). 

You can check the [Jekyll docs](https://jekyllrb.com/docs/) and their [Troubleshooting](https://jekyllrb.com/docs/troubleshooting/#configuration-problems) page and follow the steps to see the changes you make.  😌
