### ISSUE TITLE
Why is my Rails erb page not showing changes on front end?

### ISSUE THREAD

**Issue by Rajendransiva** [consul/website#18]
Hi 

We have installed the consul website and modified the ".html.erb" files but changes are not reflected on website front end.

Are we rebuild or compile it for changes to reflect into front end?if yes, please provide the steps?

Thanks

**Comment by decabeza** [comment]
Hi @Rajendransiva,

This site it's built using [Jekyll gem](https://jekyllrb.com/). 

You can check the [Jekyll docs](https://jekyllrb.com/docs/) and their [Troubleshooting](https://jekyllrb.com/docs/troubleshooting/#configuration-problems) page and follow the steps to see the changes you make.  😌
