### ISSUE TITLE
map attribution is incorrect

### ISSUE THREAD

**Issue by Seandebasti** [consul/website#21]
Hey, first: great for using an open source map as map background or your big project

Can you please try to **add** the correct attribution for the used map styles?

Due to **OSM** and **Stamen** you can find the correct attribution here:
http://maps.stamen.com/ look for "**Attribution**"
**map tiles (style)** is by Stamen, **Data** is by OSM
Leafletjs is just the origin JS-library to embed the data

You can also write:
**Leaflet | Map tiles by Stamen Design | Data by OpenStreetMap**

Leaflet=https://leafletjs.com/
Stamen=http://maps.stamen.com/
OpenStreetmap = https://www.openstreetmap.org/copyright/en

Thanks from OSM Community

**Comment by javierm** [comment]
@Seandebasti Thank you so much for reporting this issue :pray:. Correct attribution is indeed important.

@decabeza I'm afraid I don't have access to the website :thinking:. Could you a look, or maybe we can talk about how to access it?

**Comment by decabeza** [comment]
Hi @Seandebasti,

Thanks for the note! And sorry we didn't add this before. 🙏 

Now I think that's right:

![map](https://user-images.githubusercontent.com/631897/84380980-9479e400-abe8-11ea-9e57-7edcd9f6ef1b.png)
