### ISSUE TITLE
Remove Barcelona from "Who is using CONSUL?" 

### ISSUE THREAD

**Issue by xabier** [consul/website#4]
Since February, Barcelona isn't using Consul, but Decidim, a new version (non compatible) with the architecture that Consul offers. The new framework has been fully rewritten. For clarity and fairness, you should remove Decidim from decide.es list of cities.

* Legacy/Consul version deprecated: https://github.com/AjuntamentdeBarcelona/decidim.barcelona-legacy 
* New version: https://github.com/AjuntamentdeBarcelona/decidim-barcelona
* Decidim framework: https://github.com/decidim/decidim 

There is even a website specific for decidim: http://decidim.org

**Comment by bertocq** [comment]
Hello @xabier, sorry for the late response! we don't monitor this repo quite often neither invest much time in updating it.

  Any contribution is always welcome to keep the website up to date!! 🤗 So feel free to send a PR to add your city to the list 👌 Thanks!!

**Comment by xabier** [comment]
@bertocq thanks for your response, it is not a PR to add the city, but to remove it!

**Comment by andreslucena** [comment]
@bertocq we've made the PR fixing this issue, please review: https://github.com/consul/website/pull/5

**Comment by xabier** [comment]
@bertocq @voodoorai2000 @xuanxu please it is very hard for us to understand why there is no response for this Issue, nor for the PR #5 that was opened 3 months ago you asked us to do. What for? :cry:

**Comment by MariaCheca** [comment]
This issue has been solved after the recent changes made in the CONSUL website.

Thanks for contributing!
