### ISSUE TITLE
Brand guidelines

### ISSUE THREAD

**Issue by bertocq** [consul/website#6]
Add brand guidelines text somewhere (maybe better than just what we had on Consul's README)

If you want to use CONSUL logo you can [download the guidelines](https://github.com/consul/website/blob/master/consul_brand.zip?raw=true) which contains a use guide and different versions and sizes of the logo.

Si quieres usar el logo de CONSUL puedes [descargar la guía de estilo](https://github.com/consul/website/blob/master/consul_brand.zip?raw=true) que contiene una guía de uso y diferentes versiones y tamaños del logo.

**Comment by milovanderlinden** [comment]
The brand guidelines seem to have disappeared from the source. Is there a way to get them back?
