### ISSUE TITLE
Add Madrid's city council logo at the footer

### ISSUE THREAD

**Issue by bertocq** [consul/website#8]
To be consistent across all madrid's city council websites, we need it's logo at the footer (just the shield logo would do fine.. visible but discreet)

**Comment by decabeza** [comment]
Logo added! 

![footer_logo](https://user-images.githubusercontent.com/631897/34949555-b88bb418-fa10-11e7-9c4d-93e8b231dd7d.png)

Close this issue 😉

**Comment by milovanderlinden** [comment]
I have removed madrid from the footer and replaced it with the general consul logo
